import { describe, it, expect } from 'vitest';
import {
  serializeMultipartFields,
  parseMultipartFields,
  toWireBody,
  isDataUrlBody,
} from '@/components/bodyForms/registry';

const PNG_DATA_URL =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==';

describe('multipart serialization', () => {
  it('round-trips fields through serialize/parse', () => {
    const fields = [
      { name: 'name', kind: 'text' as const, text: 'Rex' },
      { name: 'photo', kind: 'file' as const, text: PNG_DATA_URL, fileName: 'dog.png' },
    ];
    const serialized = serializeMultipartFields(fields);
    expect(serialized).toContain('__multipart__');
    const parsed = parseMultipartFields(serialized);
    expect(parsed).toHaveLength(2);
    expect(parsed![0]).toMatchObject({ name: 'name', kind: 'text', text: 'Rex' });
    expect(parsed![1]).toMatchObject({ name: 'photo', kind: 'file', fileName: 'dog.png' });
    // ids are regenerated by index
    expect(parsed![0].id).toBe(0);
    expect(parsed![1].id).toBe(1);
  });

  it('returns null for non-multipart content', () => {
    expect(parseMultipartFields('{"name": "Rex"}')).toBeNull();
    expect(parseMultipartFields('not json')).toBeNull();
    expect(parseMultipartFields('')).toBeNull();
  });
});

describe('multipart toWireBody', () => {
  it('builds a real FormData with text + decoded file parts', async () => {
    const value = serializeMultipartFields([
      { name: 'name', kind: 'text', text: 'Rex' },
      { name: 'photo', kind: 'file', text: PNG_DATA_URL, fileName: 'dog.png' },
    ]);
    const body = await toWireBody(value, 'multipart/form-data');
    expect(body).toBeInstanceOf(FormData);
    const form = body as FormData;
    expect(form.get('name')).toBe('Rex');
    const file = form.get('photo') as File;
    expect(file).toBeInstanceOf(File);
    expect(file.name).toBe('dog.png');
    // PNG magic bytes decoded from base64
    const bytes = new Uint8Array(await file.arrayBuffer());
    expect([bytes[0], bytes[1], bytes[2], bytes[3]]).toEqual([0x89, 0x50, 0x4e, 0x47]);
  });

  it('skips unnamed fields', async () => {
    const value = serializeMultipartFields([
      { name: '', kind: 'text', text: 'orphan' },
      { name: 'real', kind: 'text', text: 'kept' },
    ]);
    const body = (await toWireBody(value, 'multipart/form-data')) as FormData;
    expect(body.get('real')).toBe('kept');
    expect(body.has('')).toBe(false);
  });

  it('returns undefined for corrupt multipart state', async () => {
    expect(await toWireBody('not multipart', 'multipart/form-data')).toBeUndefined();
  });
});

describe('isDataUrlBody', () => {
  it('detects data URLs', () => {
    expect(isDataUrlBody(PNG_DATA_URL)).toBe(true);
    expect(isDataUrlBody('{"json": true}')).toBe(false);
  });
});